#pragma once

using namespace std;

enum TokenType {
	PROCEDURE, READ, PRINT, ASSIGN, WHILE, IF, ELSE, CALL,
	VARIABLE, CONSTANT, CLOSEBRACKET, RELEXPR, 
	PLUS, MINUS, MULTIPLY, DIVIDE, LESSTHAN, MORETHAN,
	SEMICOLON, LEFTPARANTHESIS, RIGHTPARANTHESIS, ENDOFLINE	, MODULO,
	ENDOFPROGRAM
};

struct Token {
	TokenType type;
	string value;
};